apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job-seed.yaml

configMapGenerator:
  - name: seed-scripts
    namespace: events-api
    files:
      - scripts/seed.py

components:
  - ../../components/cluster-config-source
  - ../../components/cluster-config-replacements
