apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: events-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: debezium/connect:3.0.0.Final
          env:
            - name: BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: GROUP_ID
              value: "1"
            - name: CONFIG_STORAGE_TOPIC
              value: "connect_configs"
            - name: OFFSET_STORAGE_TOPIC
              value: "connect_offsets"
            - name: STATUS_STORAGE_TOPIC
              value: "connect_statuses"
            - name: CONFIG_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: OFFSET_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: STATUS_STORAGE_REPLICATION_FACTOR
              value: "1"
          ports:
            - containerPort: 8083
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
