apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "events-api.fullname" . }}-config
  labels:
    {{- include "events-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
data:
  APP_NAME: {{ .Values.config.appName | quote }}
  APP_ENVIRONMENT: {{ .Values.config.appEnvironment | quote }}
  APP_LOG_LEVEL: {{ .Values.config.appLogLevel | quote }}
