apiVersion: v1
kind: ConfigMap
metadata:
  name: events-api-config
  namespace: events-api
data:
  APP_ENVIRONMENT: aws
  APP_DB_HOST: rds.placeholder.invalid
  APP_DB_PORT: "5432"
  APP_DB_NAME: events
  APP_DB_USER: events_app
  APP_AWS_REGION: placeholder-region
