apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-api
  namespace: events-api
spec:
  template:
    spec:
      serviceAccountName: events-api-app
      containers:
        - name: events-api
          image: registry.placeholder.invalid/events-api-app:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: events-api-config
