apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: events-api
  namespace: events-api
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /stream
            pathType: Prefix
            backend:
              service:
                name: realtime
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: events-api
                port:
                  number: 8000
