apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - service-account.yaml

patches:
  - path: delete-postgres-deployment.yaml
  - path: delete-postgres-service.yaml
  - path: delete-postgres-secret.yaml
  - path: delete-app-secret.yaml
  - path: app-configmap-patch.yaml
  - path: deployment-patch.yaml
  - path: migration-job-patch.yaml
