apiVersion: batch/v1
kind: Job
metadata:
  name: events-api-migrate
  namespace: events-api
spec:
  template:
    spec:
      serviceAccountName: events-api-migrate
      containers:
        - name: migrate
          image: 938500344309.dkr.ecr.eu-central-1.amazonaws.com/events-api-app:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: events-api-config
