apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-api-migrate
  namespace: events-api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/events-api-iam-migration-irsa
