"""add events ingested_at

Revision ID: 80e3a2e19885
Revises: 95ac45427c05
Create Date: 2026-08-13 00:56:42.962164

occurred_at is client-supplied and can be backdated or replayed, so it
can't answer "is the pipeline actually ingesting new rows." ingested_at
is server-set at INSERT time (never updated after) and gives dbt source
freshness a signal it can trust regardless of what occurred_at says.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e3a2e19885'
down_revision: Union[str, Sequence[str], None] = '95ac45427c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'ingested_at')
    # ### end Alembic commands ###
