"""add tenant_account_changes table

Revision ID: b520db9ecd67
Revises: 80e3a2e19885
Create Date: 2026-08-16 17:37:31.525871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b520db9ecd67'
down_revision: Union[str, Sequence[str], None] = '80e3a2e19885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_account_changes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_lsn', sa.BigInteger(), nullable=False),
    sa.Column('tenant_account_id', sa.Uuid(), nullable=False),
    sa.Column('op', sa.String(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_lsn')
    )
    op.create_index(op.f('ix_tenant_account_changes_tenant_account_id'), 'tenant_account_changes', ['tenant_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_account_changes_tenant_account_id'), table_name='tenant_account_changes')
    op.drop_table('tenant_account_changes')
    # ### end Alembic commands ###
