apiVersion: v1
kind: Secret
metadata:
  name: events-api-secrets
  namespace: events-api
type: Opaque
stringData:
  APP_DATABASE_URL: "postgresql+asyncpg://events_app:events_app@postgres:5432/events"
