apiVersion: v1
kind: Secret
metadata:
  name: events-api-migration-secrets
  namespace: events-api
type: Opaque
stringData:
  ALEMBIC_DATABASE_URL: "postgresql+asyncpg://events:events@postgres:5432/events"
