"""Unit tests for EventService. These never touch a real repository —
`mock_repository` (see tests/conftest.py) stands in for EventRepository,
which is only possible because EventService depends on the abstraction,
not a concrete class (DIP). That's what "unit" means here: only
EventService's own logic is under test.

Your turn to write the test bodies. Cases worth covering:

test_ingest_calls_repository_add:
  - Set `mock_repository.add.return_value` to a fixed Event (ingest no
    longer builds the Event itself — id/timestamps beyond occurred_at are
    now DB-generated by the repository, see EventRepository.add's
    docstring — so the returned Event is whatever the repository hands
    back, same passthrough shape as TenantAccountService.create).
  - Call `await service.ingest(EventCreate(event_type="signup", user_id="u1"), TENANT_ID)`.
  - Assert `mock_repository.add.assert_awaited_once()` and that the result
    equals the mock's return value.
  - Assert the EventCreate passed to `add` has occurred_at defaulted to
    ~now since none was supplied — that's still ingest's own job.

test_ingest_honors_supplied_occurred_at:
  - Same as above but pass an explicit `occurred_at` in EventCreate.
  - Assert the EventCreate passed to `mock_repository.add` has that exact
    occurred_at, not "now" (this is the bug that got fixed earlier —
    a regression test locks it in).

test_ingest_rejects_blank_event_type:
  - Call ingest with `event_type=""`.
  - Assert it raises DomainError (pytest.raises).
  - Assert `mock_repository.add` was never called (`assert_not_awaited`)
    — a rejected event must not reach storage.

test_list_events_rejects_negative_offset:
  - Assert `list_events(offset=-1)` raises DomainError.

test_list_events_delegates_to_repository:
  - Assert `list_events(limit=10, offset=5)` calls
    `mock_repository.list.assert_awaited_once_with(10, 5)`.
"""

from datetime import UTC, datetime
from uuid import uuid4

import pytest

from app.domain.exceptions import DomainError
from app.domain.schemas import Event, EventCreate
from app.services.events import EventService

TENANT_ID = uuid4()


async def test_ingest_calls_repository_add(mock_repository):
    service = EventService(mock_repository)

    expected = mock_repository.add.return_value = Event(
        id=uuid4(),
        tenant_id=TENANT_ID,
        event_type="signup",
        user_id="u1",
        occurred_at=datetime.now(UTC),
        properties={},
    )

    result = await service.ingest(EventCreate(event_type="signup", user_id="u1"), TENANT_ID)

    mock_repository.add.assert_awaited_once()
    passed_tenant_id, passed_event_in = mock_repository.add.call_args.args
    assert passed_tenant_id == TENANT_ID
    assert passed_event_in.occurred_at is not None
    assert result == expected


async def test_ingest_honors_supplied_occurred_at(mock_repository):
    service = EventService(mock_repository)

    occurred_at = datetime.now(UTC)
    await service.ingest(
        EventCreate(event_type="signup", user_id="u1", occurred_at=occurred_at), TENANT_ID
    )

    mock_repository.add.assert_awaited_once()
    _, passed_event_in = mock_repository.add.call_args.args
    assert passed_event_in.occurred_at == occurred_at


async def test_ingest_rejects_blank_event_type(mock_repository):
    service = EventService(mock_repository)

    with pytest.raises(DomainError) as e_info:
        await service.ingest(EventCreate(event_type="", user_id="u1"), TENANT_ID)

    assert str(e_info.value) == "event_type must not be blank"

    mock_repository.add.assert_not_awaited()


async def test_ingest_rejects_missing_tenant_id(mock_repository):
    service = EventService(mock_repository)

    with pytest.raises(DomainError) as e_info:
        await service.ingest(EventCreate(event_type="signup", user_id="u1"), None)

    assert str(e_info.value) == "X-Tenant-ID header is required"

    mock_repository.add.assert_not_awaited()


async def test_list_events_rejects_negative_offset(mock_repository):
    service = EventService(mock_repository)

    with pytest.raises(DomainError) as e_info:
        await service.list_events(TENANT_ID, offset=-1)

    assert str(e_info.value) == "offset or limit values are invalid"


async def test_list_events_rejects_missing_tenant_id(mock_repository):
    service = EventService(mock_repository)

    with pytest.raises(DomainError) as e_info:
        await service.list_events(None)

    assert str(e_info.value) == "X-Tenant-ID header is required"

    mock_repository.list.assert_not_awaited()


async def test_list_events_delegates_to_repository(mock_repository):
    service = EventService(mock_repository)

    await service.list_events(TENANT_ID, limit=10, offset=5)

    mock_repository.list.assert_awaited_once_with(TENANT_ID, 10, 5)
