apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: events-api
  namespace: events-api
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: events-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
