apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml

components:
  - ../../components/cluster-config-source
  - ../../components/cluster-config-replacements
